spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    proposal:
      pending: proposal-pending.ms-credit-analysis
  proposal-concluded:
    exchange: proposal-concluded-exchange

